(defun memacs/post-init ()
  (delight '((emacs-lisp-mode "𝛌" :major)
	     (undo-tree-mode nil undo-tree) 
	     (which-key-mode "ὦ" which-key)
	     (ivy-mode "⩔" ivy)
	     (eldoc-mode "⨋" eldoc) 
	     (fundamental-mode "Ƒ" :major)
	     )
           )
  )

